### ISSUE TITLE
Add Bito.co

### ISSUE THREAD

**Issue by tiagorangel2011** [Luna-OSS/awesome-free-chatgpt#2]
Easy to reverse-engineer the extension.

**Comment by nsde** [comment]
Sorry, but I won't do that. This is my criteria for the items in my table:

- must be a website
- without login
- free
- AI responds in English (if the prompt is in English, of course)
- must be based on ChatGPT/GPT-3.5/4 or a comparable model

**Comment by tiagorangel2011** [comment]
I think Bito follows all the requirements. It has a web version, is free,
uses GPT-4, replies in English and doesn't require login.

A quinta, 22/06/2023, 1:43 da tarde, onlix ***@***.***>
escreveu:

**Comment by nsde** [comment]
I still don't understand how I can use Bito.co. Where can I write with the chatbot (without installed any extension etc.?
The website says it's an AI for developers.
So where's the chat UI?

**Comment by nsde** [comment]
Closing this for now...
